scan:
  zip:
    pipeline.0.interactions.c1_ratio:
      - -0.01389
      - -0.010914
      - -0.0079371
      - -0.0049607
      - -0.0019843
      - 0.00099214
      - 0.0039686
      - 0.006945
      - 0.0099214
      - 0.012898
      - 0.015874
      - 0.018851
      - 0.021827
      - 0.024804
      - 0.02778
  continuation: true
pipeline:
  - ground_state:
      dt: 0.005
      atom: "Eu151"
      potential:
        omega:
          - 1.0
          - 1.0
        type: "harmonic"
      backend: gpu
      B:
        q: 0.0
        p: 0.39
      initial_state: "polar"
      tol: 1.0e-8
      ddi:
        quasi_2d: true
        l_z: 0.9196
        enabled: true
      grid:
        box:
          - 12.0
          - 12.0
        n:
          - 64
          - 64
      interactions:
        omega_ref: 691.15
        c1_ratio: 0.0
        N_atoms: 50000
      n_steps: 100000
  - analyze:
      - phase_classify: {}
