units:
  B: "Gauss"
  t: "ms"
template: "klaus_magnetostir"
parameters:
  theta_tilt_deg: 35
  stir_duration: "500 ms"
  grid_n:
    - 24
    - 24
    - 12
  atom: "Eu151"
  stir_freq: 18.0
  backend: "cuda"
  c1_ratio: 0.0
  ramp_duration: "20 ms"
  chirp_duration: "50 ms"
  N_atoms: 60000
  trap_freq:
    - "50 Hz"
    - "50 Hz"
    - "130 Hz"
  B_static: "0.819 Gauss"
  grid_box:
    - 20.0
    - 20.0
    - 10.0
accuracy: 1.0e-6
