# F=5/F=7 odd-F polyhedral inert state construction + verification.
#
# Extension of paper3_audit framework to odd F values (post-修論 Paper #6
# F-systematic completion).
#
# F=5: T:E_1 (complex 1-dim, multiplicity 1)
# F=7: T:A (multiplicity 1), T:E_1 (multiplicity 1), O:A_2 (multiplicity 1)
#
# Each case verified for:
#   - spinor norm = 1
#   - ⟨F²⟩ = F(F+1) exact
#   - Schur isotropy ⟨F_a²⟩ = F(F+1)/3 for a=x,y,z
#   - ⟨F⟩ = 0
#   - group equivariance g·ζ = χ(g)·ζ
#   - β_S^{c_0} per channel
#
# Run: the archived f5_f7_polyhedral_verification.jl driver

using Test
using SpinorBEC
using LinearAlgebra
using Printf
using Random

# ----- spin matrices + Wigner D (reused from paper3_audit) -----

function spin_matrices_general(F::Int)
    D = 2F + 1
    Fz = Diagonal(ComplexF64[F - i for i in 0:(D - 1)])
    Fp = zeros(ComplexF64, D, D)
    for i in 1:(D - 1)
        m = F - i
        Fp[i, i + 1] = sqrt(F * (F + 1) - m * (m + 1))
    end
    Fm = Fp'
    Fx = (Fp + Fm) / 2
    Fy = (Fp - Fm) / (2im)
    return Matrix(Fx), Matrix(Fy), Matrix(Fz)
end

function wigner_D(F::Int, axis::Vector{Float64}, angle::Float64)
    Fx, Fy, Fz = spin_matrices_general(F)
    Fn = axis[1] * Fx + axis[2] * Fy + axis[3] * Fz
    Fn = (Fn + Fn') / 2
    ev = eigen(Fn)
    return ev.vectors * Diagonal(exp.(-1im * angle .* ev.values)) * ev.vectors'
end

function group_close(generators::Vector{<:AbstractMatrix}, tol::Float64=1e-6, max_size::Int=200)
    G = [Matrix{ComplexF64}(I, size(generators[1])...)]
    while length(G) < max_size
        prev_size = length(G)
        for g in copy(G)
            for h in generators
                gh = g * h
                if !any(norm(gh - x) < tol for x in G)
                    push!(G, gh)
                end
            end
        end
        length(G) == prev_size && break
    end
    return G
end

# ----- T group generators (subgroup of O without C_4, only C_3 + C_2) -----

function tetrahedral_gen(F::Int)
    # T group = generated by C_3 + C_2 (along 4-fold axes used as 2-fold in T)
    # Standard orientation: C_3 along (1,1,1)/√3, C_2 along z
    C3 = wigner_D(F, [1.0, 1.0, 1.0] / sqrt(3), Float64(2π/3))
    C2z = wigner_D(F, [0.0, 0.0, 1.0], Float64(π))
    return [C3, C2z]
end

function octahedral_gen(F::Int)
    C4z = wigner_D(F, [0.0, 0.0, 1.0], Float64(π/2))
    C3 = wigner_D(F, [1.0, 1.0, 1.0] / sqrt(3), Float64(2π/3))
    return [C4z, C3]
end

# ----- T group character + classification -----

function compute_T_character(group_elements, irrep::Symbol, F::Int)
    # T group conjugacy classes: e (1), 8 C_3 (θ=2π/3), 3 C_2 (θ=π)
    # 1-dim irreps:
    #   T:A: χ = (1, 1, 1)
    #   T:E_1: χ = (1, ω, 1), ω = e^{2πi/3}
    #   T:E_2: χ = (1, ω*, 1) (= complex conjugate of E_1)
    chars = ComplexF64[]
    ω = exp(2π*im/3)
    D_size = size(group_elements[1])
    Imat = Matrix{ComplexF64}(I, D_size...)
    for g in group_elements
        is_I = norm(g - Imat) < 1e-7
        g2 = g * g
        g3 = g2 * g
        is_order2 = (norm(g2 - Imat) < 1e-7) && !is_I
        is_order3 = (norm(g3 - Imat) < 1e-7) && !is_I && !is_order2

        if is_I
            push!(chars, 1.0 + 0im)
        elseif is_order3
            if irrep == :A
                push!(chars, 1.0 + 0im)
            elseif irrep == :E_1
                push!(chars, ω)
            elseif irrep == :E_2
                push!(chars, conj(ω))
            else
                push!(chars, 0.0 + 0im)
            end
        elseif is_order2
            push!(chars, 1.0 + 0im)
        else
            push!(chars, 0.0 + 0im)
        end
    end
    return chars
end

function compute_O_character(group_elements, irrep::Symbol, F::Int)
    # O group: e (1), 8 C_3 (2π/3), 3 C_2 axial (π), 6 C_4 (π/2), 6 C_2' diag (π)
    chars = Float64[]
    D_size = size(group_elements[1])

    for g in group_elements
        Imat = Matrix{ComplexF64}(I, D_size...)
        is_I = norm(g - Imat) < 1e-7
        g2 = g * g
        g3 = g2 * g
        g4 = g2 * g2
        # Strict order checks (order 1 < 2 < 3 < 4)
        is_order2 = (norm(g2 - Imat) < 1e-7) && !is_I
        is_order3 = (norm(g3 - Imat) < 1e-7) && !is_I && !is_order2
        is_order4 = (norm(g4 - Imat) < 1e-7) && !is_I && !is_order2 && !is_order3

        if is_I
            push!(chars, 1.0)
        elseif is_order3
            push!(chars, 1.0)
        elseif is_order4
            push!(chars, irrep == :A_1 ? 1.0 : -1.0)
        elseif is_order2
            push!(chars, NaN)
        else
            push!(chars, 0.0)
        end
    end

    # Refine C_2 ambiguous: axial (= squares of order-4 elements) vs diagonal
    order4_squares = Matrix{ComplexF64}[]
    Imat = Matrix{ComplexF64}(I, D_size...)
    for g in group_elements
        g2 = g * g
        norm(g2 - Imat) < 1e-7 && continue  # order ≤ 2, skip
        g4 = g2 * g2
        if norm(g4 - Imat) < 1e-7
            push!(order4_squares, g2)
        end
    end
    for i in 1:length(chars)
        if isnan(chars[i])
            g = group_elements[i]
            is_axial = any(norm(g - sq) < 1e-7 for sq in order4_squares)
            if irrep == :A_1
                chars[i] = 1.0
            elseif irrep == :A_2
                chars[i] = is_axial ? 1.0 : -1.0
            end
        end
    end
    return ComplexF64.(chars)
end

# ----- Projector + ζ construction -----

function project_onto_irrep(group_elements, chars::Vector{ComplexF64})
    P =
        sum(conj(chars[i]) * group_elements[i] for i in 1:length(group_elements)) /
        length(group_elements)
    return P
end

function find_invariant_vector(P::Matrix, D::Int; max_seeds::Int=30)
    for seed in 1:max_seeds
        Random.seed!(seed)
        v = randn(ComplexF64, D)
        ζ = P * v
        if norm(ζ) > 1e-6
            return ζ / norm(ζ)
        end
    end
    error("No invariant vector found in $max_seeds seeds")
end

# ----- Verification routine -----

function project_S_channel(ζ::Vector, F::Int, S::Int)
    total = 0.0
    for M in (-S):S
        amp = 0.0im
        for m1 in (-F):F
            m2 = M - m1
            if -F <= m2 <= F
                cg = clebsch_gordan(F, m1, F, m2, S, M)
                i1 = F - m1 + 1
                i2 = F - m2 + 1
                amp += cg * ζ[i1] * ζ[i2]
            end
        end
        total += abs2(amp)
    end
    return total
end

function verify_case(F::Int, group::Symbol, irrep::Symbol, label::String)
    @printf("\n%s\n", "="^70)
    @printf("F=%d  %s  %s:%s\n", F, label, group, irrep)
    @printf("%s\n", "="^70)

    D = 2F + 1
    Fx, Fy, Fz = spin_matrices_general(F)

    # Build group
    gens = group == :T ? tetrahedral_gen(F) : octahedral_gen(F)
    expected_order = group == :T ? 12 : 24
    G = group_close(gens, 1e-6, expected_order + 20)
    @printf("Group order: %d (expected %d)\n", length(G), expected_order)

    # Characters
    chars = group == :T ? compute_T_character(G, irrep, F) : compute_O_character(G, irrep, F)
    char_sum = sum(chars)
    @printf("Character sum: %s (expected 0 for non-trivial, |G|=%d for trivial)\n",
        string(char_sum), expected_order)

    # Projection
    P = project_onto_irrep(G, chars)
    try
        ζ = find_invariant_vector(P, D)

        # Equivariance check
        max_dev = 0.0
        for (i, g) in enumerate(G)
            dev = norm(g * ζ - chars[i] * ζ)
            max_dev = max(max_dev, dev)
        end
        @printf("Equivariance max ||g·ζ - χ(g)·ζ||: %.2e\n", max_dev)

        # Sparsity
        @printf("ζ support m ∈ {")
        for m in F:-1:(-F)
            i = F - m + 1
            if abs(ζ[i]) > 1e-6
                @printf("%d, ", m)
            end
        end
        @printf("}\n")

        # Structural sanity
        F2 = real(ζ' * (Fx*Fx + Fy*Fy + Fz*Fz) * ζ)
        Fx2 = real(ζ' * (Fx*Fx) * ζ)
        Fy2 = real(ζ' * (Fy*Fy) * ζ)
        Fz2 = real(ζ' * (Fz*Fz) * ζ)
        schur_dev = max(abs(Fx2 - F2/3), abs(Fy2 - F2/3), abs(Fz2 - F2/3))
        @printf("⟨F²⟩ = %.6f (expected %d = F(F+1))\n", F2, F*(F+1))
        @printf("⟨F_a²⟩ = (%.3f, %.3f, %.3f) (Schur: %.3f); deviation %.2e\n",
            Fx2, Fy2, Fz2, F2/3, schur_dev)
        Fx_m = real(ζ' * Fx * ζ);
        Fy_m = real(ζ' * Fy * ζ);
        Fz_m = real(ζ' * Fz * ζ)
        @printf("⟨F⟩ = (%.2e, %.2e, %.2e)\n", Fx_m, Fy_m, Fz_m)

        # Selection rule via β_S^{c_0}
        excluded = Int[]
        @printf("β_S^{c_0} per channel:\n")
        for S in 0:2:2F
            β = project_S_channel(ζ, F, S)
            if abs(β) < 1e-6
                push!(excluded, S)
                @printf("  S=%2d: β = %.6e  [excluded]\n", S, β)
            else
                @printf("  S=%2d: β = %.6f\n", S, β)
            end
        end
        @printf("Excluded S channels: %s\n", excluded)

        return ζ
    catch e
        @printf("[FAILED] %s\n", e.msg)
        return nothing
    end
end

# ----- Run all cases -----

@printf("F=5/7 odd-F polyhedral verification (Paper #6 F-systematic completion)\n")

cases = [
    # Existing
    (5, :T, :E_1, "T:E_1 complex inert"),
    (7, :T, :A, "T:A true invariant"),
    (7, :T, :E_1, "T:E_1 complex"),
    (7, :O, :A_2, "O:A_2 sign rep"),
    # Added 2026-05-12 for Year 1 Q3 F-systematic completion (task #75):
    # F=5 needs a Schur-singlet polyhedral invariant — T:E_1 (complex) fails
    # the Schur isotropy. Try octahedral A_1 / A_2 (real 1-dim).
    (5, :O, :A_1, "O:A_1 trivial invariant"),
    (5, :O, :A_2, "O:A_2 sign rep"),
    # F=13 missing entirely — add T:A, O:A_1, O:A_2.
    (13, :T, :A, "T:A true invariant"),
    (13, :O, :A_1, "O:A_1 trivial invariant"),
    (13, :O, :A_2, "O:A_2 sign rep"),
]

for (F, grp, irrep, label) in cases
    verify_case(F, grp, irrep, label)
end

@printf("\n%s\n", "="^70)
@printf("F=5/7/13 verification complete.\n")
@printf("%s\n", "="^70)
