pipeline:
  - ground_state:
      dt: 0.005
      atom: "Dy164"
      potential:
        omega:
          - 1.0
          - 1.0
          - 2.6
        type: "harmonic"
      backend: "gpu"
      B:
        theta: 0.0
        phi: 0.0
        q: 0.0
        p: 28428.0
      gauge_fix: false
      omega_ref: 314.159
      N_atoms: 60000
      grid:
        box:
          - 20.0
          - 20.0
          - 10.0
        n:
          - 32
          - 32
          - 16
      kind: "rotating_basis"
      init_m_idx: 1
      interactions:
        c1: 0.0
      init_sigma: 1.0
      n_steps: 300
  - dynamics:
      duration: 6.28
      kind: "rotating_basis"
      B:
        theta:
          duration: 6.28
          to: 0.611
          from: 0.0
        phi:
          rate: 0.0
      epsilon: 0.001
      save:
        every: 30
  - dynamics:
      duration: 15.7
      kind: "rotating_basis"
      B:
        theta: 0.611
        phi:
          rate:
            duration: 15.7
            to: 4.524
            from: 0.0
      epsilon: 0.001
      save:
        every: 30
  - dynamics:
      duration: 31.4
      kind: "rotating_basis"
      B:
        theta: 0.611
        phi:
          rate: 4.524
      epsilon: 0.001
      save:
        every: 50
