pipeline:
  - ground_state:
      dt: 0.0005
      atom: "Eu151"
      potential:
        omega:
          - 1.0
          - 1.0
        type: "harmonic"
      backend: gpu
      B:
        q: 0.0
        p: 0.0
      initial_state: "ferromagnetic"
      tol: 1.0e-8
      ddi:
        quasi_2d: true
        l_z: 0.9206
        enabled: true
      cache: "runs/shared/eu151_128x2_box16_c1r-0.01_ddi7647_q2d_lz0.9206_fm.jld2"
      grid:
        box:
          - 16.0
          - 16.0
        n:
          - 128
          - 128
      interactions:
        omega_ref: 691.15
        c1_ratio: -0.01
        N_atoms: 50000
      n_steps: 100000
  - analyze:
      - faraday:
          probe_axis: 2
          polarization: "linear_x"
          detuning: -64.0
