scan:
  comparison_runs:
    - name: "uniform_polarized"
      override:
        pipeline.0.initial_state: "ferromagnetic_min"
        pipeline.0.target_magnetization: -6.0
    - name: "fl_vortex"
      override:
        pipeline.0.initial_state: "spin_coherent"
        pipeline.0.init_state_params:
          init_vortex_charge: 1
        pipeline.0.target_magnetization: 0.0
  product:
    pipeline.0.init_state_params.init_theta:
      - 0.8
      - 1.0
      - 1.2
      - 1.5707963
    pipeline.0.interactions.c1_ratio:
      - -0.02
      - -0.01
      - 0.0
      - 0.01
pipeline:
  - ground_state:
      dt: 0.0001
      atom: "Eu151"
      potential:
        omega:
          - 1.0
          - 1.0
          - 30.0
        type: "harmonic"
      backend: "cuda"
      B:
        q: 0.0
        p: 0.0
      initial_state: "ferromagnetic_min"
      tol: 1.0e-7
      ddi:
        enabled: true
      grid:
        box:
          - 16.0
          - 16.0
          - 1.0
        n:
          - 128
          - 128
          - 8
      interactions:
        c_lhy: 1135.0
        omega_ref: 691.15
        c1_ratio: 0.0
        N_atoms: 50000
      n_steps: 100000
  - analyze:
      - phase_classify: {}
