pipeline:
  - ground_state:
      dt: 0.0005
      atom: "Eu151"
      potential:
        omega:
          - 1.0
          - 1.0
          - 1.1818
        type: "harmonic"
      backend: gpu
      B:
        q: 0.0
        p:
          to: 0
          from: 100
          scale: "log"
      initial_state: "ferromagnetic"
      tol: 1.0e-8
      ddi:
        enabled: true
      grid:
        box:
          - 20.0
          - 20.0
          - 20.0
        n:
          - 64
          - 64
          - 64
      interactions:
        omega_ref: 691.15
        c1_ratio: 0.02778
        N_atoms: 50000
      n_steps: 200000
  - analyze:
      - phase_classify: {}
