scan:
  product:
    pipeline.0.interactions.c1:
      - -5.0
      - -4.0
      - -3.0
      - -2.0
      - -1.0
      - 0.0
      - 1.0
      - 2.0
      - 3.0
      - 4.0
      - 5.0
      - 6.0
pipeline:
  - ground_state:
      dt: 0.005
      atom: "Eu151"
      potential:
        omega:
          - 1.0
          - 1.0
          - 1.0
        type: "harmonic"
      B:
        theta: 0.0
        phi: 0.0
        q: 0.0
        p: 100.0
      gauge_fix: false
      grid:
        box:
          - 12.0
          - 12.0
          - 12.0
        n:
          - 16
          - 16
          - 16
      kind: "rotating_basis"
      init_m_idx: 1
      interactions:
        c1: 0.0
        gamma_lhy: 0.0
        c_dd: 1.0
        c0: 100.0
      init_sigma: 1.5
      n_steps: 200
