scan:
  product:
    pipeline.1.duration:
      - 0.69
      - 3.46
      - 6.91
      - 10.37
      - 13.82
      - 17.28
    pipeline.1.zeeman.p:
      - 0.008
      - 0.016
      - 0.024
      - 0.033
      - 0.041
      - 0.049
pipeline:
  - ground_state:
      dt: 0.005
      atom: "Eu151"
      potential:
        omega:
          - 1.0
          - 1.0
          - 1.182
        type: "harmonic"
      backend: "cuda"
      B:
        q: 0.0
        p: 100.0
      initial_state: "ferromagnetic"
      tol: 1.0e-8
      ddi:
        enabled: true
      cache: "runs/shared/eu151_gs_p100_ferromagnetic_64.jld2"
      grid:
        box:
          - 20.0
          - 20.0
          - 20.0
        n:
          - 64
          - 64
          - 64
      interactions:
        omega_ref: 691.15
        c1_ratio: 0.02778
        N_atoms: 50000
      n_steps: 100000
  - dynamics:
      duration: 6.91
      B:
        q: 0.0
        p: 0.024
      save_every: 100
      ddi: true
      dt: 0.0005
