pipeline:
  - ground_state:
      B:
        Bz: "0.01 Gauss"
      tol: 1.0e-8
      grid:
        box:
          - 10.0
          - 10.0
          - 10.0
        n:
          - 32
          - 32
          - 32
      atom: "Eu151"
      potential:
        omega:
          - 1.0
          - 1.0
          - 1.0
        type: "harmonic"
      interactions:
        omega_ref: 691.1504
        N_atoms: 10000
      dt: 0.005
      n_steps: 3000
