# ── Dispatch backends ─────────────────────────────────────────────────
#
# Each backend implements three operations:
#
#   dispatch!(backend, entry)        # start the run; mutates entry.job_id
#   job_status(backend, entry)       # → :running | :done | :failed | :unknown
#   cancel!(backend, entry)          # request cancellation
#
# `LocalBackend` executes `run!` inline — used by tests and the
# single-machine workflow. `SlurmBackend` shells out via sbatch/squeue/
# scancel (optionally over SSH).

export LocalBackend, SlurmBackend,
    dispatch!, job_status, cancel!,
    find_job_by_name, backend_failure_reason,
    PROFILE_DIRECTIVES, next_profile, render_sbatch_script

# Profile → SBATCH directive Dict. Each profile encodes a resource
# class; the sbatch script body is identical (run_yaml + auto-save) and
# rendered on the fly by `render_sbatch_script`. Escalation
# (default → single_h100 → ...) is used by retry.jl for OOM failures
# so the next attempt has more headroom.
#
# Adding a new profile = adding a dict entry here (no new .sbatch file
# in scripts/). Tuning resource caps = editing the directives dict.
const PROFILE_DIRECTIVES = Dict{String, Dict{String, String}}(
    "default" => Dict(
        "job-name" => "spinorbec",
        "partition" => "gpu_h",
        "gres" => "gpu:h100:1",
        "cpus-per-task" => "8",
        "mem" => "128G",
        "time" => "12:00:00",
        "requeue" => "",
        "output" => "logs/%x-%j.out",
        "error" => "logs/%x-%j.err",
    ),
    "single_h100" => Dict(
        "job-name" => "spinorbec",
        "partition" => "gpu_h",
        "gres" => "gpu:h100:1",
        "cpus-per-task" => "8",
        "mem" => "256G",          # 2× memory vs default
        "time" => "24:00:00",     # 2× walltime
        "requeue" => "",
        "output" => "logs/%x-%j.out",
        "error" => "logs/%x-%j.err",
    ),
)

# Linear chain of escalation. Returns the next profile in the table, or
# `nothing` if no further headroom is registered.
const PROFILE_ESCALATION = Dict{String, Union{Nothing, String}}(
    "default" => "single_h100",
    "single_h100" => nothing,
)

next_profile(current::AbstractString) = get(PROFILE_ESCALATION, String(current), nothing)

"""
    render_sbatch_script(profile::AbstractString, config_path::AbstractString;
                         project_root=pwd()) -> String

Render the full SBATCH submission script for `profile` (looked up in
`PROFILE_DIRECTIVES`) targeting `config_path` (the YAML the job will
run). The returned string is what `SlurmBackend.dispatch!` writes to a
tmpfile and submits via `sbatch`.

Operators can override directives by mutating `PROFILE_DIRECTIVES`
in-process before dispatch, or by registering a new profile entry.
"""
function render_sbatch_script(profile::AbstractString, config_path::AbstractString;
    project_root::AbstractString=pwd(),
)
    prof = String(profile)
    haskey(PROFILE_DIRECTIVES, prof) ||
        throw(ArgumentError("unknown profile $prof; known: $(collect(keys(PROFILE_DIRECTIVES)))"))
    dirs = PROFILE_DIRECTIVES[prof]
    directive_lines = String[]
    for k in sort!(collect(keys(dirs)))
        v = dirs[k]
        push!(directive_lines,
            isempty(v) ? "#SBATCH --$k" : "#SBATCH --$k=$v")
    end
    body = """
    #!/bin/bash
    $(join(directive_lines, "\n"))
    #
    # Auto-generated by SpinorBEC.render_sbatch_script — profile=$prof.
    # Edit PROFILE_DIRECTIVES in src/workflow/autopilot/backends.jl to
    # change resource caps. Do NOT edit this file by hand; submission
    # writes a fresh script per job.

    set -euo pipefail

    cd "$(project_root)" || exit 1
    mkdir -p logs

    julia --project=. -e '
        using CUDA, SpinorBEC
        report_cuda_state()
        estimate_run_budget(ARGS[1])
        run_yaml(ARGS[1])
    ' "$(config_path)"
    """
    return body
end

# `AutopilotBackend` abstract type is declared in types.jl.

# Local in-process backend ─────────────────────────────────────────────

"""
    LocalBackend(; max_concurrent=1)

Run jobs in the same Julia process via `run!(Experiment(...))`.
`max_concurrent=1` means strict serial — appropriate for testing and
single-GPU desktops. Sets `entry.job_id = entry.content_id` for tracking.
"""
struct LocalBackend <: AutopilotBackend
    max_concurrent::Int
    _running::Dict{String, Task}    # content_id => Task
end

LocalBackend(; max_concurrent::Int=1) = LocalBackend(max_concurrent, Dict{String, Task}())

n_running(b::LocalBackend) = count(t -> !istaskdone(t), values(b._running))

function dispatch!(b::LocalBackend, entry::QueueEntry)
    n_running(b) >= b.max_concurrent && return false   # backend full
    t = Threads.@spawn try
        exp = Experiment(entry.spec_path)
        run!(exp)
    catch err
        @warn "LocalBackend run! threw" entry=entry.content_id exception=err
        rethrow(err)
    end
    b._running[entry.content_id] = t
    entry.job_id = entry.content_id
    return true
end

function job_status(b::LocalBackend, entry::QueueEntry)
    job_id = entry.job_id
    job_id === nothing && return :unknown
    t = get(b._running, String(job_id), nothing)
    t === nothing && return :unknown
    if !istaskdone(t)
        return :running
    elseif istaskfailed(t)
        return :failed
    else
        return :done
    end
end

function cancel!(b::LocalBackend, entry::QueueEntry)
    @warn "LocalBackend.cancel! is a no-op (Julia tasks can't be killed)" cid=entry.content_id
    return false
end

function find_job_by_name(b::LocalBackend, name::AbstractString)
    haskey(b._running, String(name)) ? String(name) : :no_such_job
end

function backend_failure_reason(b::LocalBackend, entry::QueueEntry)
    job_id = entry.job_id
    job_id === nothing && return "no job_id"
    t = get(b._running, String(job_id), nothing)
    t === nothing && return "unknown (task not in local table)"
    if istaskfailed(t)
        return "LocalBackend task threw: " * sprint(showerror, t.exception)
    end
    return "completed without failure"
end

# SLURM backend ────────────────────────────────────────────────────────

"""
    SlurmBackend(;
        ssh_host = nothing,             # nothing → run sbatch locally
        max_concurrent = nothing,       # nothing → let SLURM fair-share decide
        project_root = pwd(),           # working dir baked into the script
    )

Submits jobs to a SLURM scheduler. The SBATCH script is **rendered on
the fly** from `PROFILE_DIRECTIVES[entry.profile]` via
`render_sbatch_script` — no static `.sbatch` files in `scripts/`.
When `ssh_host` is set, prepends `ssh <host>` so the autopilot can
run on a non-SLURM machine (e.g. WSL) while the cluster sits behind SSH.
"""
struct SlurmBackend <: AutopilotBackend
    ssh_host::Union{Nothing, String}
    max_concurrent::Union{Nothing, Int}
    project_root::String
end

SlurmBackend(;
    ssh_host::Union{Nothing, AbstractString}=nothing,
    max_concurrent::Union{Nothing, Int}=nothing,
    project_root::AbstractString=pwd(),
) = SlurmBackend(
    ssh_host === nothing ? nothing : String(ssh_host),
    max_concurrent,
    String(project_root),
)

function dispatch!(b::SlurmBackend, entry::QueueEntry)
    profile = isempty(entry.profile) ? "default" : entry.profile
    script = render_sbatch_script(profile, entry.spec_path;
        project_root=b.project_root)

    # Write the rendered script to a tempfile alongside the run dir so
    # the on-disk record survives for forensics, then submit. The path
    # is jobname-stable: re-submission with the same content_id reuses
    # the same file.
    script_dir = joinpath(entry.run_dir, ".autopilot")
    isdir(script_dir) || mkpath(script_dir)
    script_path = joinpath(script_dir, "submit.sbatch")
    open(script_path, "w") do io
        write(io, script)
    end

    # --job-name=<content_id> enables reconciliation after mid-submit
    # crash: squeue --name=<content_id> can re-locate the job.
    cmd = if b.ssh_host === nothing
        `sbatch --parsable --job-name=$(entry.content_id) $script_path`
    else
        `ssh $(b.ssh_host) sbatch --parsable --job-name=$(entry.content_id) $script_path`
    end
    job_id = strip(read(cmd, String))
    isempty(job_id) && throw(ErrorException("sbatch returned empty job id"))
    entry.job_id = String(job_id)
    return true
end

function job_status(b::SlurmBackend, entry::QueueEntry)
    job_id = entry.job_id
    job_id === nothing && return :unknown
    cmd = if b.ssh_host === nothing
        `squeue --noheader -j $(job_id) -h -o "%T"`
    else
        `ssh $(b.ssh_host) squeue --noheader -j $(job_id) -h -o "%T"`
    end
    state = try
        strip(read(cmd, String))
    catch
        return :unknown
    end
    if isempty(state)
        return _slurm_terminal_state(b, job_id)
    elseif state in ("PENDING", "CONFIGURING")
        return :pending
    elseif state in ("RUNNING", "COMPLETING")
        return :running
    elseif state == "COMPLETED"
        return :done
    else
        return :failed
    end
end

function _slurm_terminal_state(b::SlurmBackend, job_id::AbstractString)
    cmd = if b.ssh_host === nothing
        `sacct --noheader -j $(job_id) --format=State -P`
    else
        `ssh $(b.ssh_host) sacct --noheader -j $(job_id) --format=State -P`
    end
    state = try
        first(split(strip(read(cmd, String)), '\n'))
    catch
        return :unknown
    end
    state == "COMPLETED" ? :done : :failed
end

function cancel!(b::SlurmBackend, entry::QueueEntry)
    job_id = entry.job_id
    job_id === nothing && return false
    cmd = if b.ssh_host === nothing
        `scancel $(job_id)`
    else
        `ssh $(b.ssh_host) scancel $(job_id)`
    end
    try
        run(cmd)
        return true
    catch err
        @warn "scancel failed" job_id=job_id exception=err
        return false
    end
end

# Reconciliation: look up a job by its sbatch --job-name. Returns the job
# ID if SLURM still sees it, :no_such_job if not, nothing on probe error.
function find_job_by_name(b::SlurmBackend, name::AbstractString)
    cmd = if b.ssh_host === nothing
        `squeue --noheader -h --name=$(name) -o "%i"`
    else
        `ssh $(b.ssh_host) squeue --noheader -h --name=$(name) -o "%i"`
    end
    out = try
        strip(read(cmd, String))
    catch err
        @warn "squeue --name probe failed" exception=err
        return nothing
    end
    isempty(out) && return :no_such_job
    return String(first(split(out, '\n')))
end

# Post-mortem reason from sacct (OOM_KILLED / TIMEOUT / NODE_FAIL / ...).
function backend_failure_reason(b::SlurmBackend, entry::QueueEntry)
    job_id = entry.job_id
    job_id === nothing && return "no job_id"
    cmd = if b.ssh_host === nothing
        `sacct --noheader -j $(job_id) --format=State,Reason,ExitCode -P`
    else
        `ssh $(b.ssh_host) sacct --noheader -j $(job_id) --format=State,Reason,ExitCode -P`
    end
    line = try
        first(split(strip(read(cmd, String)), '\n'))
    catch
        return "sacct probe failed"
    end
    return String(line)
end
