#!/usr/bin/env python3
"""
Forensic index regenerator — Upgrade D (1000-turn design).

Reads state.json history + per-turn output files, regenerates:

    runs/_loop/INDEX.md              (chronological turn table)
    runs/_loop/by_subagent/<name>.md (reverse index per subagent)
    runs/_loop/by_paper/<paper>.md   (reverse index per manuscript)
    runs/_loop/by_tag/<tag>.md       (reverse index per topic tag)

Per `long_horizon_design.md` §2 D:
- Codex CLI AGENTS.md durable-spec pattern [OpenAI 2025] applied
  per-turn
- Letta context repositories pattern [Letta 2025] for reverse lookup

Turn metadata sources (in priority order):
1. Frontmatter in `runs/_loop/<dir>/turn_N.md` if present (preferred)
2. state.json history entry (always available)
3. Inferred from filename / directory

Run modes:
    turn_index_regen.py              # regenerate all indices
    turn_index_regen.py --check      # validate without writing
"""

from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LOOP_DIR = ROOT / "runs" / "_loop"
STATE = LOOP_DIR / "state.json"


SUBAGENT_DIRS = ["director", "theorist", "research", "sim", "judge"]


def _read_frontmatter(path: Path) -> dict:
    """Parse YAML frontmatter from a turn markdown file."""
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    if not m:
        return {}
    fm: dict = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        k, _, v = line.partition(":")
        k = k.strip()
        v = v.strip()
        # Crude list parse: [a, b, c]
        if v.startswith("[") and v.endswith("]"):
            fm[k] = [x.strip().strip('"').strip("'") for x in v[1:-1].split(",") if x.strip()]
        else:
            fm[k] = v.strip('"').strip("'")
    return fm


def _collect_turn(turn_n: int, history_entry: dict | None) -> dict:
    """Collect all metadata for a turn from history + frontmatter scan."""
    entry = {
        "turn": turn_n,
        "judge_status": (history_entry or {}).get("judge_status", "?"),
        "directive_action": (history_entry or {}).get("directive_action", "?"),
        "directive_label": (history_entry or {}).get("directive_label", "?"),
        "commit": (history_entry or {}).get("commit"),
        "branch": (history_entry or {}).get("branch"),
        "wall_time_sec": (history_entry or {}).get("wall_time_sec"),
        "effective_tokens": ((history_entry or {}).get("tokens_used") or {}).get("effective_full_rate"),
        "subagents_run": [],
        "topic_tags": [],
        "paper_section": None,
        "depends_on": [],
        "produces": None,
    }

    # Scan each subagent dir for turn_N.md frontmatter
    for sa in SUBAGENT_DIRS:
        cand = LOOP_DIR / sa / f"turn_{turn_n}.md"
        if cand.exists():
            entry["subagents_run"].append(sa)
            fm = _read_frontmatter(cand)
            if fm:
                if "topic_tags" in fm and isinstance(fm["topic_tags"], list):
                    for t in fm["topic_tags"]:
                        if t not in entry["topic_tags"]:
                            entry["topic_tags"].append(t)
                if "paper_section" in fm and not entry["paper_section"]:
                    entry["paper_section"] = fm["paper_section"]
                if "depends_on" in fm and isinstance(fm["depends_on"], list):
                    for d in fm["depends_on"]:
                        if d not in entry["depends_on"]:
                            entry["depends_on"].append(d)
                if "produces" in fm and not entry["produces"]:
                    entry["produces"] = fm["produces"]

        # critic audit lives at judge/turn_N_critic_audit.md
        if sa == "judge":
            crit = LOOP_DIR / sa / f"turn_{turn_n}_critic_audit.md"
            if crit.exists():
                entry["subagents_run"].append("critic")

    return entry


def _gather_all_turns() -> list[dict]:
    """Walk state.json history + filesystem to enumerate every turn."""
    if not STATE.exists():
        return []
    state = json.loads(STATE.read_text())
    history = state.get("history") or []
    by_turn = {h["turn"]: h for h in history if "turn" in h}

    # Also scan directories for any turn_N.md not in history
    seen_turns: set[int] = set(by_turn)
    for sa in SUBAGENT_DIRS:
        d = LOOP_DIR / sa
        if not d.is_dir():
            continue
        for f in d.glob("turn_*.md"):
            m = re.match(r"turn_(\d+)\.md$", f.name)
            if m:
                seen_turns.add(int(m.group(1)))

    return [_collect_turn(n, by_turn.get(n)) for n in sorted(seen_turns)]


def _format_chronological_index(turns: list[dict]) -> str:
    lines = [
        "# Loop turn index — chronological",
        "",
        "Auto-regenerated by `.claude/scripts/turn_index_regen.py` after each turn.",
        f"Total turns: {len(turns)}",
        "",
        "| Turn | Subagents | Verdict | Action | Label | Tags | Cost (eff) | Commit |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for t in turns:
        tags = " ".join(t["topic_tags"]) if t["topic_tags"] else "—"
        subs = "+".join(t["subagents_run"]) if t["subagents_run"] else "—"
        cost = f"{t['effective_tokens']:,}" if isinstance(t["effective_tokens"], int) else "—"
        commit = (t["commit"] or "—")[:7]
        lines.append(
            f"| T{t['turn']} | {subs} | {t['judge_status']} | "
            f"{t['directive_action']} | {t['directive_label']} | "
            f"{tags} | {cost} | {commit} |"
        )
    return "\n".join(lines) + "\n"


def _format_by_subagent(turns: list[dict]) -> dict[str, str]:
    out: dict[str, list[dict]] = defaultdict(list)
    for t in turns:
        for sa in t["subagents_run"]:
            out[sa].append(t)
    rendered: dict[str, str] = {}
    for sa, tlist in out.items():
        lines = [f"# Turns where `{sa}` ran", "", f"Total: {len(tlist)}", ""]
        for t in tlist:
            tags = " ".join(t["topic_tags"]) if t["topic_tags"] else "—"
            lines.append(
                f"- **T{t['turn']}** [{t['judge_status']}] "
                f"`{t['directive_label']}` — tags: {tags}"
            )
        rendered[sa] = "\n".join(lines) + "\n"
    return rendered


def _format_by_paper(turns: list[dict]) -> dict[str, str]:
    out: dict[str, list[dict]] = defaultdict(list)
    for t in turns:
        ps = t.get("paper_section")
        if not ps:
            continue
        # Extract paper id robustly. Accept:
        #   "paper3/sign_pattern_lemma1_general_S.md" → paper3
        #   "docs/manuscript/papers/paper4_chaotic_dynamics/main.md"
        #     → paper4_chaotic_dynamics
        #   "paper4_chaotic_dynamics" → paper4_chaotic_dynamics
        # T8 fix 2026-05-15: previously took split("/",1)[0] which
        # collapsed full paths to "docs".
        m = re.search(r"(paper\d+[a-zA-Z0-9_-]*)", str(ps))
        if m:
            paper_id = m.group(1)
        else:
            # Fall back to first non-"docs"/"manuscript"/"papers" segment
            segs = [s for s in str(ps).split("/")
                    if s and s not in {"docs", "manuscript", "papers", ".md"}]
            paper_id = segs[0] if segs else "unclassified"
        out[paper_id].append(t)
    rendered: dict[str, str] = {}
    for paper_id, tlist in out.items():
        lines = [
            f"# {paper_id} — loop contributions",
            "",
            f"Turns referencing manuscript section `{paper_id}/...`: {len(tlist)}",
            "",
        ]
        for t in tlist:
            lines.append(
                f"- **T{t['turn']}** [{t['judge_status']}] "
                f"`{t['directive_label']}`"
                + (f" → {t['paper_section']}" if t.get("paper_section") else "")
            )
        rendered[paper_id] = "\n".join(lines) + "\n"
    return rendered


def _format_by_tag(turns: list[dict]) -> dict[str, str]:
    out: dict[str, list[dict]] = defaultdict(list)
    for t in turns:
        for tag in t["topic_tags"]:
            out[tag].append(t)
    rendered: dict[str, str] = {}
    for tag, tlist in out.items():
        lines = [f"# tag `{tag}` — turn history", "", f"Total: {len(tlist)}", ""]
        for t in tlist:
            lines.append(
                f"- **T{t['turn']}** [{t['judge_status']}] "
                f"`{t['directive_label']}`"
            )
        rendered[tag] = "\n".join(lines) + "\n"
    return rendered


def regenerate(check_only: bool = False) -> dict:
    turns = _gather_all_turns()
    if not turns:
        return {"status": "OK", "turns": 0, "wrote": []}

    chrono = _format_chronological_index(turns)
    by_sa = _format_by_subagent(turns)
    by_pp = _format_by_paper(turns)
    by_tg = _format_by_tag(turns)

    wrote: list[str] = []
    if not check_only:
        idx = LOOP_DIR / "INDEX.md"
        idx.write_text(chrono)
        wrote.append(str(idx.relative_to(ROOT)))

        for sa, txt in by_sa.items():
            d = LOOP_DIR / "by_subagent"
            d.mkdir(parents=True, exist_ok=True)
            f = d / f"{sa}.md"
            f.write_text(txt)
            wrote.append(str(f.relative_to(ROOT)))

        for pp, txt in by_pp.items():
            d = LOOP_DIR / "by_paper"
            d.mkdir(parents=True, exist_ok=True)
            f = d / f"{pp}.md"
            f.write_text(txt)
            wrote.append(str(f.relative_to(ROOT)))

        for tg, txt in by_tg.items():
            d = LOOP_DIR / "by_tag"
            d.mkdir(parents=True, exist_ok=True)
            # Sanitize tag for filename
            safe = re.sub(r"[^a-zA-Z0-9_-]", "_", tg)
            f = d / f"{safe}.md"
            f.write_text(txt)
            wrote.append(str(f.relative_to(ROOT)))

    return {
        "status": "OK",
        "turns": len(turns),
        "subagent_indices": list(by_sa.keys()),
        "paper_indices": list(by_pp.keys()),
        "tag_indices": list(by_tg.keys()),
        "wrote": wrote if not check_only else [],
        "check_only": check_only,
    }


def main() -> int:
    check_only = "--check" in sys.argv
    result = regenerate(check_only=check_only)
    print(json.dumps(result, indent=2))
    return 0 if result["status"] == "OK" else 1


if __name__ == "__main__":
    sys.exit(main())
