scan:
  comparison_runs:
    - name: "fm_min"
      override:
        pipeline.0.initial_state: "ferromagnetic_min"
    - name: "polar"
      override:
        pipeline.0.initial_state: "polar"
    - name: "fl_vortex"
      override:
        pipeline.0.initial_state: "fl_vortex"
  auto_rotate_on_mz: true
  zip:
    pipeline.0.target_magnetization:
      - -6.0
      - -4.0
      - -3.0
      - -2.0
      - -1.0
      - -0.5
      - 0.0
  continuation: true
pipeline:
  - ground_state:
      method: "itp"
      dt: 0.001
      atom: "Eu151"
      potential:
        omega:
          - 1.0
          - 1.0
          - 1.1818
        type: "harmonic"
      backend: "cuda"
      B:
        q: 0.0
        p: 0.0
      initial_state: "ferromagnetic_min"
      tol: 1.0e-7
      ddi:
        enabled: true
      target_magnetization: -6.0
      grid:
        box:
          - 20.0
          - 20.0
          - 20.0
        n:
          - 64
          - 64
          - 64
      interactions:
        c_lhy: 1135.0
        omega_ref: 691.15
        c1_ratio: 0.0
        N_atoms: 50000
  - ground_state:
      tol: 1.0e-8
      backend: "cpu"
      method: "lbfgs"
      n_steps: 500
  - analyze:
      - phase_classify: {}
