pipeline:
  - ground_state:
      dt: 0.005
      atom: "Eu151"
      potential:
        omega:
          - 1.0
          - 1.0
          - 2.6
        type: "harmonic"
      backend: "cuda"
      B:
        theta: 0.0
        phi: 0.0
        q: 0.0
        p: 26700.0
      gauge_fix: false
      omega_ref: 314.159
      N_atoms: 60000
      grid:
        box:
          - 20.0
          - 20.0
          - 10.0
        n:
          - 48
          - 48
          - 24
      kind: "rotating_basis"
      init_m_idx: 1
      interactions:
        c1: 0.0
      init_sigma: 1.5
      n_steps: 250
  - dynamics:
      duration: 6.28
      kind: "rotating_basis"
      save_every: 30
      B:
        theta:
          duration: 6.28
          to: 0.611
          from: 0.0
        phi:
          rate: 0.0
      epsilon: 1.0e-6
  - dynamics:
      duration: 15.7
      kind: "rotating_basis"
      save_every: 30
      B:
        theta: 0.611
        phi:
          rate:
            duration: 15.7
            to: 1.0
            from: 0.0
      epsilon: 1.0e-6
  - dynamics:
      duration: 314.0
      kind: "rotating_basis"
      save_every: 50
      B:
        theta: 0.611
        phi:
          rate: 1.0
      epsilon: 1.0e-6
