# Build a precompiled sysimage so each TSUBAME job starts ~30-60 sec
# faster (no SpinorBEC JIT cost on first call).
#
# Run ONCE on the TSUBAME login node (or a compute node if PackageCompiler
# requires hardware-specific compilation). Subsequent jobs add
# `--sysimage=spinor_sysimage.so` and skip the SpinorBEC JIT.
#
# Usage:
#   julia --project=. scripts/tsubame/build_sysimage.jl
#
# Output: spinor_sysimage.so (typically 200-400 MB, depends on Julia version)

using Pkg
Pkg.activate(@__DIR__ * "/../..")

# PackageCompiler is itself a heavy dep — install on demand only when this
# script runs, so the regular project doesn't carry the weight.
Pkg.add("PackageCompiler")

using PackageCompiler

# Precompile statements: ideally generated by `--trace-compile=*.jl`
# during a representative run, then fed to `precompile_execution_file`.
# For now we exercise the rotating_basis pipeline with a tiny config so
# the most-used methods land in the sysimage.
const PRECOMPILE_SCRIPT = joinpath(@__DIR__, "_sysimage_precompile.jl")

if !isfile(PRECOMPILE_SCRIPT)
    open(PRECOMPILE_SCRIPT, "w") do io
        write(
            io,
            """
            # Auto-generated by build_sysimage.jl — exercises the public API
            # surface so PackageCompiler captures the right method specialisations.
            using SpinorBEC

            # Tiny pipeline exercise (no full ITP — just method coverage).
            grid = make_grid(GridConfig((8, 8, 8), (4.0, 4.0, 4.0)))
            sys = SpinSystem(1)
            psi = init_psi(grid, sys; state=:polar)

            # Touch the rotating_basis path
            ws = SpinorBEC.make_rotating_basis_ws(grid, 1, zeros(8, 8, 8);
                p=1.0, q=0.0, c0=1.0, c1=0.0, c_dd=0.0, gamma_lhy=0.0,
                theta_func=t -> 0.0, phi_func=t -> 0.0,
                theta_dot_func=t -> 0.0, phi_dot_func=t -> 0.0,
                gauge_fix=false)
            SpinorBEC.normalize_rotating!(ws)
            """,
        )
    end
end

@info "Building sysimage (this may take 5-15 minutes)…"
out_path = joinpath(@__DIR__, "..", "..", "spinor_sysimage.so")
create_sysimage(
    [:SpinorBEC];
    sysimage_path = out_path,
    precompile_execution_file = PRECOMPILE_SCRIPT,
)

println("\n✅ Sysimage built: $out_path")
println("Add to your job script:")
println("  julia --project=. --sysimage=spinor_sysimage.so ...")
