pipeline:
  - ground_state:
      dt: 0.0005
      atom: "Eu151"
      potential:
        omega:
          - 1.0
          - 1.0
        type: "harmonic"
      backend: gpu
      B:
        q: 0.0
        p: 0.0
      initial_state: "polar"
      tol: 1.0e-7
      ddi:
        quasi_2d: true
        l_z: 0.9196
        enabled: true
      cache: "runs/shared/eu151_96x2_box24_c1r0.0_ddi7647_q2d_lz0.9196_polar.jld2"
      grid:
        box:
          - 24.0
          - 24.0
        n:
          - 96
          - 96
      interactions:
        omega_ref: 691.15
        c1_ratio: 0.0
        N_atoms: 50000
      n_steps: 100000
  - analyze:
      - phase_classify: {}
