pipeline:
  - ground_state:
      dt: 0.005
      atom: "Eu151"
      potential:
        omega:
          - 1.0
          - 1.0
          - 2.6
        type: "harmonic"
      backend: gpu
      B:
        theta: 0.0
        phi: 0.0
        q: 0.0
        p: 26700.0
      gauge_fix: false
      grid:
        box:
          - 10.0
          - 10.0
          - 5.0
        n:
          - 16
          - 16
          - 8
      kind: "rotating_basis"
      init_m_idx: 1
      interactions:
        c1: 0.0
        gamma_lhy: 0.0
        c_dd: 0.0
        c0: 3786.0
      init_sigma: 1.5
      n_steps: 250
  - dynamics:
      duration: 62.83
      kind: "rotating_basis"
      save_every: 50
      B:
        theta: 0.611
        phi:
          rate: 0.0
      epsilon: 0.001
